README.md
=> add install + usage examples in the README.md

environment.yml, slcl1butils/scripts/do_IW_L1C_SAFE_from_L1B_SAFE_prun.py
minor modif in `do_IW_L1C_SAFE_from_L1B_SAFE_prun` and add `environment.yml` that was missing
=> fix packaging dependencies

pyproject.toml, slcl1butils/compute/compute_from_l1b.py, slcl1butils/scripts/do_IW_L1C_SAFE_from_L1B_SAFE.pbs, slcl1butils/scripts/do_IW_L1C_SAFE_from_L1B_SAFE_prun.py
=> L1C processor fix issues #2

slcl1butils/get_polygons_from_l1b.py, slcl1butils/scripts/do_IW_L1C_SAFE_from_L1B_SAFE.pbs, slcl1butils/scripts/do_IW_L1C_SAFE_from_L1B_SAFE.py, slcl1butils/utils.py
address memory error for 2 km tiles L1B -> L1C processing
=> xndindex added + minor corrections

slcl1butils/coloc/coloc.py, slcl1butils/scripts/do_IW_L1C_SAFE_from_L1B_SAFE.py
=> fix resampling ancillary

docs/basic_api.rst, docs/cwave.rst, slcl1butils/__init__.py, slcl1butils/compute/compute_from_l1b.py, slcl1butils/compute/macs.py, slcl1butils/compute/stack_wv_l1c_monthly.py, slcl1butils/plotting/display_one_spectra.py, slcl1butils/scripts/do_IW_L1C_SAFE_from_L1B_SAFE.py, slcl1butils/scripts/do_IW_L1C_SAFE_from_L1B_SAFE_prun.py, slcl1butils/scripts/do_WV_L1C_SAFE_from_L1B_SAFE.py
=> improve L1C (classic and stacked) production

slcl1butils/coloc/coloc.py, slcl1butils/scripts/do_IW_L1C_SAFE_from_L1B_SAFE_prun.py
#41 introduced a new error that is fixed in this PR.
=> Fix interpolation anc

slcl1butils/coloc/coloc.py
we found that the interpolation of ancillary fields works fine in the different situation spotted with a clearer/simplified code.
=> simplification of the ancillary interpolation 

slcl1butils/compute/cwave.py
1 - add parenthesis for spectrum normalisation
2 - dky.dky -> dkx.dky (in spectrum normalisation)
3 - change of definition in alpha_phi (swith k_rg, k_az)
=> debug of cwave definitions

docs/basic_api.rst, docs/index.rst, pyproject.toml, slcl1butils/__init__.py, slcl1butils/coloc/coloc_WV_WW3spectra.py, slcl1butils/config.yaml, slcl1butils/legacy_ocean/ocean/spectrum_private/spectra_functions.py, slcl1butils/legacy_ocean/ocean/xPolarSpectrum.py, slcl1butils/legacy_ocean/ocean/xspectrum.py, slcl1butils/plotting/display_one_spectra.py, slcl1butils/scripts/do_IW_L1C_SAFE_from_L1B_SAFE.pbs, slcl1butils/scripts/do_IW_L1C_SAFE_from_L1B_SAFE.py, slcl1butils/scripts/do_IW_L1C_SAFE_from_L1B_SAFE_prun.py, slcl1butils/scripts/do_WV_L1C_SAFE_from_L1B_SAFE.pbs, slcl1butils/scripts/do_WV_L1C_SAFE_from_L1B_SAFE.py
=> Add colocation WV with WW3 spectra

pyproject.toml, slcl1butils/legacy_ocean/ocean/xspectrum.py
try to fix issue with distutils and python3.12 probably related to pyfftw dependency introduction
=> pyfftw remove

slcl1butils/coloc/coloc.py, slcl1butils/coloc/coloc_WV_WW3spectra.py, slcl1butils/compute/stack_wv_l1c_monthly.py, slcl1butils/raster_readers.py, slcl1butils/scripts/do_IW_L1C_SAFE_from_L1B_SAFE.pbs, slcl1butils/scripts/do_IW_L1C_SAFE_from_L1B_SAFE.py, slcl1butils/scripts/do_IW_L1C_SAFE_from_L1B_SAFE_prun.py, slcl1butils/scripts/do_WV_L1C_SAFE_from_L1B_SAFE.py, slcl1butils/scripts/do_WV_L1C_SAFE_from_L1B_SAFE_prun.py, slcl1butils/utils.py
=> integrate ww3hindcast ancillary dataset

.github/workflows/publish.yml
use same workflow for pypi publishing as the one used in slcwinddirection for instance.
=> pypi workflow upgrade

docs/conf.py, pyproject.toml, slcl1butils/compute/stack_wv_l1c_monthly.py
=> correction on dependencies + stacking

slcl1butils/coloc/coloc_IW_WW3spectra.py
=> add missing coloc_IW_WW3spectra.py

slcl1butils/compute/stack_wv_l1c_monthly.py
motivation: reduce the number of inodes to create. (zarr creates lots of files and is not the most suitable format for sharing through https protocol)
=> WV stacking replace zarr by nc

slcl1butils/utils.py
=> activate the new directories tree YYYY/JJJ/..SAFE/

slcl1butils/compute/stack_wv_l1c_monthly.py
=> change engine for netcdf save

slcl1butils/coloc/coloc_IW_WW3spectra.py, slcl1butils/scripts/do_IW_L1C_SAFE_from_L1B_SAFE.py
We have a new source of WW3 spectra; the CCI sea state config runs. This PR enable the co-localisation with this product.
=> modification to enable WW3 spectra from CCI sea state runs to added

pyproject.toml
=> add rioxarray

slcl1butils/scripts/do_WV_L1C_SAFE_from_L1B_SAFE.py
Fix related to config file key.
=> l1c_wv_version -> l1c_wv_productid
